# Generated by Django 2.2.2 on 2024-02-21 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nopassword', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 11, 50, 19, 46044), null=True),
        ),
    ]
